// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfigiybuidsiankvusfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmaWdpeWJ1aWRzaWFua3Z1c2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MDAzMTQsImV4cCI6MjA1OTE3NjMxNH0.EcT6rDFas4FFwO_J3SqWI3kiYv5fQiIZkjrX1SYC6VE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);